# Generated by Django 5.1 on 2024-10-21 18:45

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=60)),
                ('feedback', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OpenAIConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use', models.CharField(default='Ninguno', help_text='Cual es el Uso de esta configuración', max_length=50)),
                ('model', models.CharField(default='gpt-3.5-turbo', help_text='Modelo de OpenAI a utilizar.', max_length=50)),
                ('temperature', models.FloatField(default=0.7, help_text='Controla la aleatoriedad de las respuestas (0 a 2).')),
                ('max_tokens', models.IntegerField(default=1600, help_text='Número máximo de tokens en la respuesta.')),
                ('system_message', models.TextField(default='Eres un asistente que responde en español y conoce sobre gimnasios y las máquinas.', help_text='Mensaje del sistema que guía las respuestas de OpenAI.')),
            ],
            options={
                'verbose_name': 'Configuración de OpenAI',
                'verbose_name_plural': 'Configuración de OpenAI',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('weight', models.IntegerField(null=True)),
                ('height', models.IntegerField(null=True)),
                ('age', models.IntegerField(null=True)),
                ('gender', models.CharField(max_length=10, null=True)),
                ('image', models.FileField(null=True, upload_to='')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='MachineInfoGeneratedAI',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom_maquina', models.CharField(max_length=100)),
                ('tipo_maquina', models.CharField(max_length=100)),
                ('MachineInfo', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('AI_use', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='huggingface.openaiconfig')),
            ],
        ),
        migrations.CreateModel(
            name='Ejercicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo_muscular', models.CharField(max_length=25)),
                ('niv_dificultad', models.CharField(max_length=25)),
                ('repeticiones', models.IntegerField()),
                ('series', models.IntegerField()),
                ('instrucciones', models.TextField()),
                ('videoDemostrativo', models.CharField(max_length=255)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='huggingface.machineinfogeneratedai')),
                ('ia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='huggingface.openaiconfig')),
            ],
        ),
        migrations.CreateModel(
            name='RoutineGeneratedAI',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('routineGenerated', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('AI_use', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='huggingface.openaiconfig')),
                ('usuario', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
