# Generated by Django 5.1 on 2024-09-24 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huggingface', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='height',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='weight',
            field=models.IntegerField(null=True),
        ),
    ]
