# Generated by Django 5.1 on 2024-10-15 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huggingface', '0002_alter_customuser_age_alter_customuser_gender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=60)),
                ('feedback', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
