# Generated by Django 5.1 on 2024-10-21 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huggingface', '0002_alter_machineinfogeneratedai_nom_maquina_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
