# Generated by Django 5.1 on 2024-11-09 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huggingface', '0003_alter_customuser_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='routinegeneratedai',
            name='objective',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
