# Generated by Django 5.1 on 2024-10-15 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huggingface', '0004_alter_customuser_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenAIConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(default='gpt-3.5-turbo', help_text='Modelo de OpenAI a utilizar.', max_length=50)),
                ('temperature', models.FloatField(default=0.7, help_text='Controla la aleatoriedad de las respuestas (0 a 2).')),
                ('max_tokens', models.IntegerField(default=1600, help_text='Número máximo de tokens en la respuesta.')),
                ('system_message', models.TextField(default='Eres un asistente que responde en español y conoce sobre gimnasios y las máquinas.', help_text='Mensaje del sistema que guía las respuestas de OpenAI.')),
            ],
            options={
                'verbose_name': 'Configuración de OpenAI',
                'verbose_name_plural': 'Configuración de OpenAI',
            },
        ),
    ]
