# Generated by Django 5.1 on 2024-11-12 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huggingface', '0005_alter_routinegeneratedai_objective'),
    ]

    operations = [
        migrations.AddField(
            model_name='routinegeneratedai',
            name='horarioExcerciseGen',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='routinegeneratedai',
            name='principalExerciseGen',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
