# Generated by Django 5.1 on 2024-11-22 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huggingface', '0006_routinegeneratedai_horarioexcercisegen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='subscription',
            field=models.BooleanField(default=False),
        ),
    ]
