# Generated by Django 5.1 on 2024-10-16 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huggingface', '0006_fitnessroutine'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
