# Generated by Django 5.1 on 2024-10-21 18:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huggingface', '0007_routinegeneratedai'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineInfoGeneratedAI',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('MachineInfo', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('AI_use', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='huggingface.openaiconfig')),
                ('usuario', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
